source "https://rubygems.org"

gemspec

group :development do
  # Nous dépendons de Vagrant pour le développement, mais nous ne l'ajoutons pas en tant que dépendance
  # de gemme car nous nous attendons à être installés dans l'environnement
  # Vagrant lui-même en utilisant `vagrant plugin`.
  gem "vagrant", :git => "https://github.com/mitchellh/vagrant.git"
end

group :plugins do
  gem "vagrant-aws" , path: "."
end
