require 'rubygems'
require 'bundler/setup'
require 'rspec/core/rake_task'

# Synchronisez immédiatement tous les stdout afin que des outils comme
# buildbot puissent se charger immédiatement dans la sortie.
$stdout.sync = true
$stderr.sync = true

# Accédez au répertoire de ce fichier.
Dir.chdir(File.expand_path("../", __FILE__))

# Cela installe les tâches qui aident à la création et à la publication
# de gemmes.
Bundler::GemHelper.install_tasks

# Installez la tâche `spec` afin que nous puissions exécuter des tests.
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = "--order defined"
end
# La tâche par défaut consiste à exécuter les tests unitaires
task :default => :spec
