# -*- mode: ruby -*-
# vi: set ft=ruby :

# Exiger le plug-in du fournisseur AWS et le module YAML
require 'vagrant-aws'
require 'yaml'

# Lire le fichier YAML avec les informations d'instance
instances = YAML.load_file(File.join(File.dirname(__FILE__), 'instances.yml'))

# Spécifiez la version de Vagrant et la version de l'API Vagrant
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'

# Créer et configurer la ou les instances AWS
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Utiliser une boîte AWS factice
  config.vm.box = 'aws-dummy'

  # Spécifier les informations d'authentification AWS
  config.vm.provider 'aws' do |aws, override|
    # Specify access/authentication information, keypair
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name = instances['keypair_name']

    # Spécifiez la région et l'ID AMI
    aws.region = instances['region']
    aws.ami = instances['ami']
    aws.security_groups = instances['security_groups']
    aws.instance_type = instances['instance_type']

    # Spécifiez le nom d'utilisateur et le chemin de la clé privée
    override.ssh.username = instances['user']
    # Modifiez la ligne suivante avec vos informations correctes
    override.ssh.private_key_path = '~/.ssh/aws_rsa'
  end # config.vm.provider 'aws'
end # Vagrant.configure
