---
- hosts: "all"
  vars:
    github: "https://github.com"
  become: "yes"
  remote_user: "vagrant"

  tasks:
  - name: Assurez-vous que le répertoire /usr/local/bin existe
    file:
      state: "directory"
      path: "/usr/local/bin"
      owner: "root"
      group: "root"

  - name: Créer un répertoire temporaire
    tempfile:
      state: "directory"
      suffix: "tmp"
    register: "tmpdir"

  - name: Télécharger et extraire l'archive ksonnet de GitHub
    unarchive:
      src: "{{ github }}/ksonnet/ksonnet/releases/download/v0.10.2/ks_0.10.2_linux_amd64.tar.gz"
      dest: "{{ tmpdir.path }}"
      remote_src: "yes"
      owner: "root"
      group: "root"

  - name: Copiez le binaire ks versionné dans l'emplacement final
    copy:
      src: "{{ tmpdir.path }}/ks_0.10.2_linux_amd64/ks"
      dest: "/usr/local/bin/ks-0.10.2"
      remote_src: "yes"
      owner: "root"
      group: "root"
      mode: 0755

  - name: Créer un lien symbolique vers le binaire versionné
    file:
      path: "/usr/local/bin/ks"
      src: "/usr/local/bin/ks-0.10.2"
      state: "link"
      owner: "root"
      group: "root"

  - name: Supprimer le répertoire temporaire
    file:
      path: "{{ tmpdir.path }}"
      state: "absent"
