
Vagrant.configure("2") do |config|
  config.vm.box = "azure"

  # utiliser la clé ssh locale pour se connecter à la boîte de vagabondage distante
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.vm.provider :azure do |azure, override|
    azure.location = "westus"

    # remplacez-le par votre ID de ressource d'image gérée
    azure.vm_managed_image_id = "/subscriptions/{subscription_id}/resourceGroups/{group}/providers/Microsoft.Compute/images/{image_name}"
  end

  config.vm.provision "shell", inline: "Coucou tout le monde"
end
