---
- hosts: "tag_tool_ansible"
  connection: "local"
  gather_facts: false
  vars:
    region: "<insérer la région AWS ici>"

  tasks:
  - name: "Supprimer les instances EC2 balisées du groupe de sécurité"
    ec2:
      state: "running"
      region: "{{ region }}"
      instance_ids: "{{ ec2_id }}"
      group_id: ""
    delegate_to: "localhost"
      
  - name: "Mettre fin aux instances EC2 marquées"
    ec2:
      state: "absent"
      region: "{{ region }}"
      instance_ids: "{{ ec2_id }}"
      wait: true
    delegate_to: "localhost"

- hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    region: "<insérer la région AWS ici>"

  tasks:
  - name: "Supprimer le groupe de sécurité"
    ec2_group:
      name: "ansible-sec-group"
      description: "Nouveau SG pour les instances créées par Ansible"
      region: "{{ region }}"
      state: "absent"
