# encoding: utf-8
# Copyright (c) Microsoft Corporation. Tous les droits sont réservés.
# Sous licence sous la licence MIT. Voir Licence dans la racine du projet pour les informations de licence.

source "https://rubygems.org"

gemspec

group :development, :test do
  # Nous dépendons de Vagrant pour le développement, mais nous ne l'ajoutons pas 
  # en tant que dépendance de gemme car nous nous attendons à être installés dans 
  # l'environnement Vagrant lui-même en utilisant `vagrant plugin`.
  gem "vagrant", git: "https://github.com/mitchellh/vagrant.git", tag: "v1.9.2"
end

group :plugins do
  gem "vagrant-azure", path: "."
end
