# encoding: utf-8
# Copyright (c) Microsoft Corporation. Tous les droits sont réservés.
# Sous licence sous la licence MIT. Voir Licence dans la racine du projet pour les informations de licence.

require 'rubygems'
require 'bundler/setup'
require 'rspec/core/rake_task'

$stdout.sync = true
$stderr.sync = true

Dir.chdir(File.expand_path('../', __FILE__))

Bundler::GemHelper.install_tasks

# Installez la tâche `spec` afin que nous puissions exécuter des tests.
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = '--order defined'
end
# Default task is to run the unit tests
task :default => :spec
