
Vagrant.configure("2") do |config|
  config.vm.box = "azure"

  # utiliser la clé ssh locale pour se connecter à la boîte distante Vagrant
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.vm.provider :azure do |azure, override|
    azure.location = "westus"

    # remplacez cet URI par le blob de votre compte de stockage dans la même région que celle spécifiée ci-dessus
    azure.vm_vhd_uri = "https://vagrantimages.blob.core.windows.net/vhds/xenial-server-cloudimg-amd64-disk1.vhd"
    azure.vm_operating_system = "Linux"
  end

  config.vm.provision "shell", inline: "echo Coucou tout le monde "
end
