# -*- mode: ruby -*-
# vi: set ft=ruby :

# Toute la configuration de Vagrant se fait ci-dessous. Le "2" dans Vagrant.configure configure la version de configuration 
# (nous prenons en charge les styles plus anciens pour une compatibilité descendante).
# Veuillez ne pas le modifier à moins que vous ne sachiez ce que vous faites.

Vagrant.configure('2') do |config|
  config.vm.box = 'azure'

  config.vm.provider :azure do |azure, override|
  end
end
